apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgB5qBgYEHsNVltQJrmh4bAPg4g2+VjM/FujFxQSkr8GzMAznRHBd7UuN2x9EZ+3n0cbKTvjGQLeciwa6ZKQppx6W6nqNVkufSVjxvQApzgPk+dtl0WYTVjwAsWmLcZrHnbnLZpigS4TpDQ6NVNq2TQ83JSHtr5Xd5bWD5zmWDxvIZ00PyflZ0g/80EVqWaskW9Cg5d5YIhsySN/zbCNZhMt/vg5jOJ01AFbiLwBwZEdDKBeD+H4z5phUDMY8ozDcBJJIeb69gim3HQA2TGV+6tDq7Ky9r5UFWR4H4uFhpUvPyIOwTBPhALS6RTmEZ4ExVdbygRNytyKBhoFrK0ckhq2XmmVlgkCRuzhEAO7GhYAM1RhLOG6w+vAkAPB0ekc9JYsnppRhLMJnOkgZZD24zdEW15beyDybaWFYKG0bSzodjfjQyaJYJ8VQU2kNTYgq/ru0T1Tl01iThjBTLwLqhkup5NEwovTODMuYLhLEF1SphOdpDxnSEcc/5+9qcJUqXcy2VIyPAqb00yErJ57LPDk6L73BAJkKpKU5rqKMsFKEPeYYVuS7d/4ZnoKQeqlxAh/pUbre4qp4r7NDT1kXk8KcFaaq7qR+pkfEmlXnKkDcm7Q+QkmZpKkEmYWausfW2JhLVLS3f7g6vFKRbZavjP7e+vo94U+3RxkUyH03BwDHmI+L+ozWxZ551yP9K4qgGwQUnEv/gKPldfLgXpHJc9CIo89wTkRiSj87BWQjqa1n5REham/iiBKfa1WhgbXZclEE84uoXhojEz6CybvFb0td6M0gOnNGzdFdSCMldaK2rB9AmD+pBnMgz8oSuE0iK5v/j4XTSmQyF0hYrol08hXALNV1XM36K7ElY52zW5YtO/LlKIID7iTVpVW2teyAsceU2dJULLs89SR5hirOkwpVxnI+Q==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

