apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCZ7OHoDUq2T6jwWA7bPanPH94+gJSDhUQWfYShJAngw53C8QdBCTdOAx8+U6NukHxWqI0KYraV1g+9/P/y4g0T8gOSgePCA7WASUI0z355Z4p+ep0ot6TnQisDPhXnVaZVVA5FG7QzaTFHv2xLhx3K0WXLvBO9KOK3Ofmf46CcBq+PUKu4fSWRSZdQMdXfFCV/cSw4WRDHlGrdiswhPYdEZZQWUaYVpNmWISvxHJQxMY8JkDnNFL1IHtUBq/ax1Ir2t1w80SYL04BfmPn7sWqoBWXB8cqNzDFsBKMGN9+pOBS04sKck3m1mMiBaep/KUnga9DTBQyrYSIf2aWqDJ69+nJ12OcBcY5Xx2y5K86yi1+0zIzrdTOwpd6MvHOS2S+de/APZh7v9MysSXCBOL3VaXg9tSiv9UvqX1gsauGaRiQNk6yJjhiLuU4joau0pZJoeMab4JOxEgi15HkXFldZYHKWwcsouw8RPpqgU54gAziNtjblElOTK3pJivmI63O38lfMowNF/eNmsKe7e6MHNsmJZBH+yT9In78t3dHhEokMZGc06+FDMBunadgOiLwsfo/bCf6rzAYlL205b0HJ9NCeDLTeeESshchmcbJ0EQjOifDhVAg8Xm0xSOWbaeCdCsYs1fv01S8tYvgmaPv22CjEuRI/xBwnEmeHAGvRGCjJ5584kH5rP8NiXRul+peJsh4WxRkPv4MStHNbyxjfJKZQgTmcG71WEeTyFDgPxhukaCgKarZlUNRPwPSUmGxHGGNLjc3tF+OmS7WtPuucRQzvqYIpMOyaWa53n1XZvy1dF7G/toaZazfgANaIRCmxxzAyazHxekDKifh5W5RfeiU2zvtIyIgb/4ZcECBtltxH516pE5IBmopechMclpxsi0DTgLPAEd3j4FOsC/gaci+BqQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

