apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCAgRekCYTNv3iqMnX3gce+4HzPgEK8zDKTMI+r3jky88aSAFvtUdP0o4f9nX3INOtqmVhG5bC5bH2GPbjKIIB2oYoP6KXh/Po9s6S0Ud0CP8Ezrdgtu9MjWXhX1ffnxvOST31l35XDNkFRpd8c9h0YooMUfGWdLIp6EHznuIS3dB/4clR5h/sCcPi7Iud11PX5/fI8/OAHJnP817Lq+4hy7NRGepMT26DTdMuqIFLEZHaixVz+8bUJEPeAveT2A6zIcie41rhVt3MrO/eESB13aX3oIcRNLvyGZ0wkboLX9nV39hr1kbbpTr8x4o3EmCwKG5oa5UfeKrpFn2mVukjE96BewU/Kj5rAd/cG9CYfhXZUxnz61S/RI3rMv2xbldlUre0npHBY4bc69v42cDeVebzSBkiCf/iCicEP8g+jB16/M9iisaa0YZDJfzYiUbwdLO7pTu23bWva6lws+9ktAIWKa59xYBB0Mp6EzEWTU4wzLw+2VQmsSgDsggTeXfavCgXYvVdD2xgzN2YXqAkBQsEbtTB0w0oMWDIx5uaSr/A8m2jQVh08vAkeqMooDlKptPtFqTzJuyzai1MFATACr7sy1T58DAb9JQArTeR348VQKt+Z99wtKBlz6Fju9fshHQmSUR7AQSRowiZgPtc3iCorX4Z01s33mw4JtW5MTfpsa3/hVzbObXLfhKk8mmpK1yBdHW61523SkQiNfI+LW7grht5fl0Bsq60yvbhZtL9FEdbNxv0m4Oh9BpUsQrerhpal22dQ7q+zZHhlxENbluvlEmVkKbhDsCOKfTF29U+gTwEBTcZPD8X/6Vj11bexS3L1nAxXek6YUrQurR/NwDVSNH4nzB6zyXmlYefXNRvNSXeFnGcK/8BZxir3J0msL1Semtum1XyMbQ+DglzXH1Kk7Q==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

