apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBxCSODCU8wA8zAO4zvGc2RbgPK+0GzKmxQfjSkuFq9brXKQfHLBjeRUWcYJf8Tr++zfG16GZMfTp7hEVjVtAGUiPjNO994QNKcB0L4XG6iTHZWrPgIFh5I7XL2iHjeQR/E+cF3t+tMg2M43DH1XsCN5TdYsYAnV6pkiRQHCniZpD8UcyUXoNI7avfkjAjpSpdFlsrghxDcZGIjQaymUSDwhKHs5j8QeX6U663dW9LCJiHm/TBe9gsTtCA6LaukHbvoiYWP+OLW53Bhf4JRVMJfTJJAOH5U5q1bY0dfqIUFY9vmuicJkmbGkcdoQvwKstYc8X33SpoQe/chWzIEQan92sMydzdttBXKK9x6TKw7XfCLOY67YxHVMAvqjVhgZJTERo46fYjo0vwXZNZLdT3vLYN6Y1eMuVzc+856iI7NPLiyJSt71czCy5a8Q5XrzXRmpuSzG9RxQlU7PYXpKlXlVewKTp+hS2cTop2GW38uTkOmTagP4CUCXay1S0XoH/ECFrl2vFkXtuxk73/Cdrm0fFslmzM71rJU456KouynQWuDPGIOHEECzOdCN03sAcPsJLm+bSJw9HIg4pdtTn/Plzma9zPVufvwWLeeWUyYluC2AbmRXyRMjP0+qQ/A+M2VWudIJg+P81gR0rADoApNEurXTrW8yVcsyVXshEvWQ3A0LbnMZiRozK5nWiXlEZquOWxw25b7+72XUuH8BGHoyDjExKOMDwyIitf+ekQSgcQ0lTOUT/mgTyhJq1beloy4h/IFPO0v2gshNPuBbolbDJO0DKuX777gqUA2rhb1FefJiCWF1s9jGUsEfrmVgy735oA7lf+nDP2nWDAr2wSDsHQkSnaPSDU07EvIN5NSdfQ5ugfEAFq9Vz/j4fJcdVxd/LxVFw01TVW9AvQcxDSHp3IfDg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

