apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAqBws0r4Sihm9D88QGMw+LfDjQIFBlg9jPJrRJWMcpDOBZnG3rwbLDLl3XJvN/CR52vuHYoQMvhnk7mBFF2WOa2g6YgJG36PFHFeQ6To0ApnOqyyyrRS7KjVHB2y8VO93/DtZm4febaPQXeGUiGwRGEcY3t64QZoaSxxUKUUfsy6xX4olnQkg/Z5K08Fs3a+/y0RoGOpgtmnYXx9mhKyAKh2x9i6B6kdlKFQER0ikj9Ga3Sg/1vkfxHqA/U6j9SsqT5EKfQKGrRU+JrH9O1LHEFniBnC6LEh/2UiKD15dlZCUttARtY3C4A99v6G8qsul53AT8YPHxmmz0Ix4FqlfbCBM6vKvGms42n6YOcQD+58V269IFyGtjdD6BU/qTTKDcgBxdVY4BfaS96xWRYi766YpKE5aKRJP1BE/luwvngUCjTRoRMSnb3udArgTetY3GCPPG/xILfWazGWm16tuB9rTPsuazd6kWm2lAVBaWBHbBM730fScvB79+Ol1nz/ngtzoj/AD/R4d7s1cxS0g8VPPs+9t8ZleL1TWs0FhveKFV+DLtoPfXnJyoOL6e5uE9yO1IXh3Kg1SA0tt7krcy5i9hjjbS9SmuUINtVUWVPi2NZ1TJIrpGB7Q1WyZvlR+chUAMGbZexlLPBqTjEgbTa9MyzrxlRTR61M6r58KFogQvIS++6UP+mBtpdoGkIFNsE41+O6to++7v7PLvZX9CQmgjvQoBEGFkeE2azAAt09rTlrd6mX5tsYSPY3Cf2Wp9B5y4OPRLcnNhjiCRG1pjRTvdNcS/wyZRgklES8bmNKdmbjSG9vJKc87Y7KSppfRSykkG7wygajQ1q3JhQOMpmkC/PRDxN7w8epmLmxIs6ZE6xBGXkV13wesG/AEakPYsiMP6FzsQSIND/oqOQ7OmgbtvXw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

