apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBk5/dpA1FCaFqQlnXerki6s+8zjEVJEqABjO5IkGpN4QkViUJxxQXFjHJX/YYHsYigcvr2taJPwpiK7IvwwfqZaDO1cnzDZzlZ4RrSQZEcacsmdhyBHB2iCs7XFIq+6RCOArL2nmGBIKk66Ur1DTbjCwVbddQKebnEU14umj1scXyHjAjorXqJGpOLPp5NQg9oXSNBr0giIcl5NbkmAQbp/mxF8kaHIf7PtW8eeyUDDQVZ82vywGSXvMWW9V7VU0q4IwVWfFKfsUq2YMl46nwtOAzS+m+5Z3D07ERGYRRR2aNhawqchUuKu6xUZjmrxSIJudSk9fAziaCeJa8HqVmJl5mh3kWIrGe78XRxHDwsFEtHZzSGmRUEZ+vSeAoMv6FnjZrU9jqdogs0xiTict5v0sR8pjIWdcnLJW9JXEhJRQvubQ5PPmvA3GPYHKhQ/CbAh+7jjFbRYnTfNwPNdkladJ7FjeC1lKwX+fQ5fNqnILbVlRurPCQm2To9ATqru+du0v8J3b+E3Dgrzp42q2mIjph/XHtKgNgQQAIrb2gRJ+xZc7apIILDu0urKDZk30a0bp5eEw8txIR1U4R4uifeJZTm6aJzguDSu2AmpwSzlwS+L6zGJJjdT8AGpG8Ga8r2lJfE8FCdxuYSXLo76IRa8Bi/QNIOSoj+eB0SA60Czi/UNk17HeV2GOi9yF2yz83cd2TbX7DtOn7TSbOIcYo4Lrh5rsHos6JYiFjFiy5Zngz69E3ONQjMfkt3i1WvAZ340lWUlvqSmDysqIX1QRB674yzRGJ8zQC5RuydislgcoOVVC8tcPZrGfqJqxOvw8LWZfzwh1iCuOgK4JA1AGTAlQerasbbjOQh1JpgVbqqTT6s0Wr17Esmm9IadxBm7S6YL1LOBFuJyCPcy9R+hqYW4f1SEg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

