apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBXjkKkRJNf7yQeR1NdHRRU0SnQahwb6lnRAVej+A82yItL3z3XaOu2Ip/lNcVnukQvtCtOlPsvNuqNjcckn8mteV18uHs0+1yRBJB/8+mpU4Lc7FwjMm2q5Ry2yDDnaLhdHmFhnAJ+Q7w35/v1IZPNZVIHHEa9xutnX6xs+wK9eU1aYxEASAeVfg8xntCinojpCT6PmjecRu3j8bjfe37H0TH3P8va9Dz+DWUYvHCqT19gXYlyvE47k70vVQrS71wuAjU6TZJtzRgU7hcFJGZclk3S13XpP81S+QHd/1avuZkZX5ORl9lq/Aj1cqOe86peS6LFL854UmRkqTIJZDmFoe7zD+HyEI1rOGZKL8WYKHR+hEb6LfEMe/PwzPMCngcxvgf9ahafWQvIrJ/wXsM8veuuL9DXH4RF3kzVqet/MHffgf2CE3S6ydJUBwv6IHifEPFMbKAQ1xwxg2qRcws+dEsNJNRT87TnI9puaxwZrr9065jJcRhs5KQTx6qLp93Uwgq+CCfu7MbIobsNUW8Uj3p7+5a6KpYeXGyqfbS9a6WJYRMFNJRv4fJHwI7xxbNZky2afaGIagXiBkr6pQAMnbZOIra3+9AAZC8kIy4QqVnAk9dsoj1xyJIVux6JiTMd6099PsfTzpjBdqU5xCet2GD8v9w6PO7ms4aYKBXLte0lyXXDBoVXycGNXmeFRKWuCdZ37Y27YfFIV4s/lItRpM/1T6W4lBcKVM0HMCsDQTE3EhP1X1//eNkRfVSefERnCcbVtMDJ6x6OjrWXIZ+jCZdgEyzLcJ7qz8Ya9aoUqC8xQDiPwVA72kPtZPnH1Qnpn0fK5S4EjVYqA2hbZZQHN1h4jGevFt9XfFFXd9qUo8o7k8L08Zm+hnRPqXOYCRu/TlOvD6gWJoOo3FsAJqW2jcmYBQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

