apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCMIMZ0BbiE23t5nGrz59Fj/2JcxGQz+60/dfpS2pSZORQJm0p5wZBZlKDEB8EvUECr0WItMeEr+UucY4phSy5ZEzhO9qBqWcxS/x0g3PD43agso7arxiVNtIOXIO1MtK98iqtKofqmczfLkz3XzwgKRz3cutTaJabizzLXjFxI8vlG+UO3iZ//oZsE+6K2vE6FfmF6BDMePCC+4/LzwF2Jh2CFoNYIKRVbnz+YsPY6BGIaV0XkGBBVJc/irKg8oJH+m+l+EgMQSlrLKFdP0+4iIDS8H29CI7XCau40O5oka3Tj/mLEhjkYVBFL/z9YT383tusU0RmyZHSQ2UoZsdmQrldQRnR29yELTGctczLr4fV6C5T+S60VMh29JSpys7AYJ/ypnoeLFZbFhEifasqgLkmbnIjam0zl6CTQu3Ki83VON/hzumSJ5xVnFsV1jEpwRAnPxPXNZGLU3SaUPRRcU9EXuI3eH/Ml2mks2yQSrzOqAp60MGOcCosXO0YDaoyy6gZu8XBdB4Lx7BdVhzJECtcT2yYJ3DvpWwaArcjA59W45OW70T2/iREt9HPFOIH3v2XHXD6MF7BRWxuR/LU0bB1FfO2FIY/NBaPvkTj9KhPTZ9JsGv1JXd2rl6pfNbOr58CjzL9ifx65m7pvJ5gZ/eWbhMMuxEHaEznvKCYirjjUsue80YZsIE4jRFEyTX8hAnHkEISVVmzLRF0wU3eh2rALvLuAVrkS/7D30aq064fCieRzBGfG
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

