apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBedHcaUQQeD9Dn627EpuemViONjY2ZUFbAaoeCHSd00IEdhxANZjV+2nzEnDZ6oci/x2CPVISYhlF9cPJ//H/WzUiPOMjKI7QsyUyemlzfny4+UfkylLF5HRZybKAFwWln1J1Q4lVxpPoNRdW7ObTL946I9bOYKTay0nRKDI5/hWQSeusmpWaFJWQJXjSEKghnHMi5t2hV7IoYmuNakDynE9pN8GK7JVJCmnMhJkOEpza4f0Alv8vNoFKDMZX+dJuC8FJBwDnGvAtdnlj8QpqJg4wKC7sj8Yb+0+3tILtGIRptoV4yHjmScqjPoT3QPhcL1l17tcf3adolzdfDvJHRCdB+0VjzH/Ol8T2T8C664CxzedDoJgR3pj0U/38Ffp0rYRIDlFjSt8Mj/ii7P7KV117zlmDb+nusDcFoNw9K4uptE3MANXK/jzBVg2VyNeFMXByU42N+S1i2vgd0CC7lrN2W4XKQ1lwCvHg5cgHCB7lT5DXU2by7NhPOSAW1RLo+QmJTzcyWy/i0CplNGeeEWOWmaa17VI8C676wsGKplx+fpNR5nZtXhrnp6ZXwpTg9VZcIxanBGRAT3LqnrUNCqNyDxkhlcZ7Tg0nV7Oop+ac/jNgGJc0mQWKSe3JLM53buzw9YfZ0j5JGP9oasmi1Zf/gToGPzEWErPPbc0SgeGdQM4gg0zMFchCyYoElHkneCWNh2yWOYVyJCi8xEnQ2xMYbNeoKZ9P0FX3+HaK7N3mX15ucS4W3
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

