apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCrpi79lEe+FW7Cl28VOQp3xzqKlOtxY7d7jX8K1Q6SwMd8ymMrbdbHsEnwoLZNyvcukGwCspFih+HdMpcx7bJ2kCvwh/LaUxZlv1g59g63fUuu+AMH1LipeL0ogza43zPyYH16+R8lA8z4+xBKUowfpbGoJCDVeM4T4tzGkTZIVcIp3VThQlrF0ZHjS6/EUhmmEXWjIDZSJB/TsE5+pvFqs3pHN1fb7s46ErpAt/23k5NZDGRRQzvPUj1+vSV9wBq+qxIgb0VwnRneJ3wsmP/aEK6T00/z+kHWGR5lRZVqxNHUvk/htVVrfyC0KM4VAf4w+5YLecELpxuxWKzpRtAarzKewPoRFkCtWgCfEFSUPlNlVi97tpO1v+WqwD8JRyDNDpUN8DCP71g1HY4wzkmsIaqF9vPpD6MRtEePvDCh7dd5+wW+9RMysb27m9++n+ZUQavXEW7nHu+7V+LduKV6hNj6T2e7mWOnjBcAumUj/AVFZ4NgTSvz1L5XNRjuly6WNQS5G4Bgm7BdpQiYmQBcUIummGaKZGMshuYPzzv84ML9xEsXBciVYJkUz08N6kxv/xJma+fGPtN8+wiLTNIsUCIhf7d9WWiUY8V6p9B7GqTogPHLndO3+UOW0HNp3HP3G5Qy2kqsJG28OzeHH2BPfI2zPTb27j5b1RY9ZC81L6OdxE/qpZFXSmMVeNvOERVLiJNK+xhbvDXJrUORJMmpyaXR7gRAkGA5BV5jK0Ulekf60Q+mcHAv
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

