apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAgGyDdbQd7ADdLpGzkyk69mCb7UC9rKqd2Fn4a31VeIt+eeALzj4F8C8/8UrqWj33WAKgehnZ6cCPQdJexisE1j1UQ+hn0/V5z/2eNBSyQMYvKR9yyt5Fk9CH8UTcAzf2mqimqyuCmId6MOevi5C0MT5Bxip7MJg3jUOSYh0cjTBg0eDiRaLiG+Neu/dOL8vE0M7PAviCLKMFu1TVHJJzD6l+aU1l/qVZEdjCcBJKW43QKzpiJKVvarZvTcUzUabeZUegMr7HucecninppjvNK4227SkiuJrZT2bfOZ3UYeLiDY3QFP2tox9Q6ZNkn3DjZ9ZhnUecFVa+YtcUn2YSzDYBAz8ONHo8lr/84fyiC9yOqhEBQrA7FaWl5UroByyAk1jfh6N33ZkOWde2PRmIXm/yUEeNr9trg6jSrrSEr2CAOi1bugE+OHYs6CidaZ1ZOvTevJsS7nva1mxsK84JSZBkjsXeZpRz+utS5qrEsJ0CPApxXKf0ol48/ZrvNO0s9yi+OfyWX41l1z0m35SIe9aJW/lmlm5lOIL77LcZHEy9qZjbmDktvuSAy724ARXEJy1XgGtVvqeKlK6mEUh4X5oEMZvp4XQGHtGhA/2UlFo12fb8tpU0/2C9R3/SL/J4jrNimbIHdG/MhOvm4WpayoF0UzGKZwn5/Q3QxsnznZhPNKVcqPS9GpUaiHaX+AH6iXJup5crMsbZ8FhsH71dP8JcscIS4/o/UcsnyPSroLujJaE+Un6iI
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

