apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgArcUgFnfuJJ8KoBGgnSsGJZTCkuxHoDkIRVVNpusSQcBmEPZWAi9p/kTmBUdcmsJrn0scUMJhbUmChIdct1y9Fu6eyq+5bvAnF3sZLh4UOi8j7WoZmkc9UjHM8LCFesVawzHy35RLk7VlHEiXkbkMstKyO02pvUqzg8lYO4tPgywAOCCS1ujKo7rFQxvV/1UjPSm9Y5oLYK20wuJR+e42T+T/0VJjWldGoOL3hqivke5doHhE4UN/opNlwwJ7EULFRiruq4tNY+91lvw2BrZBxmOyN5HGbhNKRMoSF6gW4wo6q5Xzwg6lvU01qhbmA+wBdtkqadzkLDqYttEkZ/leQivGxq/dUku9ckWuF8Iy+xJ6NeADFbGPQ1HzlaszuVWqNmbAklHrVlQ7HYSU50tEIosxPwUrIsUcUEmmhGv3UEpcz37Jo66KMZRNO+Y02aVVp+m3hgLZzOGMe/zdjz5SK0YOtP4UDmVV0gc/lMcQAVRbzw2UVvWMRdL/GKNWkrSIo/v5nMHie908/zajPL/1mSY3RzBSSM42xtcWuz5nPy1cfnG5CkLLgqcGQOkA3GKgBm/sZ1UifAEq5R1y45XR1jsbqBL1Q1T4+iWEqj2BfYbhx+gBIg7bNy0t4Idz3Ri6SGjVzCQzAU/m9jWpRtPRRx3z8+w5TSl/mcdFPB0hh8YRemRgsgNHeqz8j0AXvRwy9H6wGnTfOdtYVohWx/us++7C6r9zStxUWWFDwlHhl/FlEiZgBt61o
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

