apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBkp26TdmiX/zBc5bK0puUTlKVdAXY8Pk5+sPMLgMTOn/SP31hcpInCOnXLSoUtcaicq4ufpM9gZI4IQqCheTOe8Mnj8kGH6rSjgOKmFTbG7iLWajapajhFp4HNPVoSScHu+mX3fxnTqGqXDEe5uWQEBjwAFl8I9Ft1Ffurneb5XVUvpzq30fBSNNS6M13wrkGVtyFF/9TGdZIYoKw0r8i1RZ65LWdiVQztazKi2Co37swczuQXdXko7tfMqntS9lqQtjOQpxBNl7wpFvMq7aerXmmDeGWLKxcumFodNpSugnoDEiXAUtxDmL97Ivn1KYdGL6XUezfsW8RemkmJQWjMZbVaL1AqexNgZKP5loaHrGRPxyljraYE6s+TL5UNEAleEC9OPI4VSphhLslcX+H88/v42Nw1nTMbIB3hqTdO2Lyi5qLyFQHQON8OE9SeIkT5CzqYZszrsllk6mhWlOKz4xtS/3QGKMrtaYNmfyNqzkHlXWX5SAMJTsD1iWub0SEmO9KKJ3iQxvNkLXhPM0IrTs97xXVlYOSQFA28+3I8Z7J6kByBIxdgBfYKf787i8JTc/ng++RANH6QeeLq1w9PvYq0xzWYOBS7ZBEa262/vOyQCmMTzqWZCgA/11gBlpSQH8249WXxs3dtZGVNTnq+JrF+3TNmxHPWNJT0POS9UUFaKVd40jP/9Z/FQKz6sIZu6EscMLASTrQFEVB9W5wHET16wkAQ0XBeKqI37VNzzbSREqfhYaGT
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

